[build]
  base    = "docusaurus-dev-guide/"
  command = "npm run build"
  publish = "docusaurus-dev-guide/build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
